# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e252ae9be1e2111a5e78a23ff1441b13919bd0615333eeddcf25510a9718d9ff863dea6b0de9f0c36f86333f74070ae6f235a4b776407a288f90a248d727923

test:
  secret_key_base: ace77147c7578c1336d1cfc0d2b10d53ca5b946688330ee040377f7c31498ff16df55c97d0ec3cda9aa7eabcd7ce9ed9c3d06458ba449c713d26bab110986b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
